version: '3'
services:
  ecommerce-ui:
    image: ecommerce-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true # Enables polling for hot reload
      - VITE_BASE_URL=${VITE_BASE_URL}
      - VITE_FIREBASE_KEY=${VITE_FIREBASE_KEY}
      - VITE_AUTH_DOMAIN=${VITE_AUTH_DOMAIN}
      - VITE_PROJECT_ID=${VITE_PROJECT_ID}
      - VITE_STORE_BUCKET=${mern-ecommerce-c46dd.appspot.co}
      - VITE_MESSAGING_ID=${VITE_MESSAGING_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_MEASUREMENT_ID=${VITE_MEASUREMENT_ID}
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
